spring.application.name=Exammodule
server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.admin.email=admin@gmail.com
app.admin.password=admin@123
